curl -H 'Content-Type: application/json' \
-d '{"bucket": "airSensor", "fields": ["temperature"], "measurements": ["airSensors"], "range": {"start": "-10000000", "stop": ""}, "filters": [] }' \
-X POST http://localhost:8080/generate-query