
services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - dev-network

  influxdb:
    image: influxdb:2.7
    ports:
      - "8087:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_DB=exampledb
      - INFLUXDB_HTTP_CORS_ENABLED=true
      - INFLUXDB_HTTP_CORS_ALLOWED_ORIGINS=*
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - dev-network

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ALLOW_EMBEDDING=true
  #    - GF_AUTH_ANONYMOUS_ENABLED=true
  #    - GF_AUTH_ANONYMOUS_ORG_NAME=influx-UI-UG-10
  #    - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    volumes:
       - grafana-storage:/var/lib/grafana:rw
       - ../.grafana_config/grafana.ini:/etc/grafana/grafana.ini:rw
    networks:
       - dev-network


volumes:
  influxdb-storage:
  grafana-storage:

networks:
  dev-network: